#!/usr/bin/env python
#coding:utf-8

# 使用递归输出九九乘法表
def printline(n, m):
    '''输出第m行'''
    print(f'{n}X{m}={n * m}', end=" ")  # 输出一项
    if n < m:
        printline(n + 1, m) # 输出第m行第n+1个

def print99(n = 1, m = 9):
    '''输出9行'''
    printline(1, n) # 输出第n行
    print('')
    if n < m:
        print99(n + 1, m)  # n + 1


print99()

print('---' * 10)

# 使用循环输出九九乘法表
for i in range(1,10):
    for j in range(1, i+1):
        print(f'{j}x{i}={i*j} ', end="")
    print('')
